### ISSUE TITLE
Exception: URL /{key} has parameter key, but no method parameter matches

### ISSUE THREAD

**Issue by byebyebt** [reactiveui/refit#901] opened 2020-04-12 11:57 UTC
I'm trying accessing a webapi like "http://ip:port/Search/", it need a object parameter that has many fields( in Request body ).  I define the interface as :

```
[Post("/Search")]
Task<string> Search([Body] TSearcher searcher ,[Header("Authorization")] string authorization = default);
```
I have checked all fields vlaue very carefully to ensure its crrect, but I received a exception with message "URL /{key} has parameter key, but no method parameter matches"， that‘s a puzzling message, because there aren't key parameter in the url. what's it means on earth? would somebody can help me? ( Refit version is 5.1.54 )

**Comment by Dreamescaper** [comment] 2020-04-12 16:40
Could you provide example project reproducing the issue?
I tried to reproduce it with the following code, but it works perfectly fine for me.

```csharp
using System.Threading.Tasks;
using Refit;

namespace Test
{
    public interface ITestInterface
    {
        [Post("/Search")]
        Task<string> Search([Body] Searcher searcher, [Header("Authorization")] string authorization = default);
    }

    public class Searcher
    {
        public string Term { get; set; }
    }

    public class TestClass
    {
        public static async Task Main(string[] args)
        {
            var service = RestService.For<ITestInterface>("http://api");
            var res = await service.Search(new Searcher { Term = "test" });
        }
    }
}
```

**Comment by clairernovotny** [comment] 2021-02-04 23:33
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:33 UTC
