### ISSUE TITLE
Unable to resolve service for type IInterfaceService

### ISSUE THREAD

**Issue by zhoucm666** [reactiveui/refit#717] opened 2019-07-29 08:54 UTC
How to use extension method below to inject typed HttpClient?

public static IHttpClientBuilder AddRefitClient(this IServiceCollection services, Type refitInterfaceType, RefitSettings settings = null)
        {
            return services.AddHttpClient(UniqueName.ForType(refitInterfaceType))
                           .AddTypedClient((client, serviceProvider) => RestService.For(refitInterfaceType, client, settings));
        }
i.e.
var refitInterfaceType = typeof(IInterfaceService);
services.AddRefitClient(refitInterfaceType);

**Comment by benjaminhowarth1** [comment] 2019-08-28 20:05
Ooh, generic interface injection using Reflection. Honestly, I don't think we've covered this as a use case before (hence AddRefitClient<T>), but I can see how that might be beneficial. Let me dig & get back to you.

**Comment by benjaminhowarth1** [comment] 2019-12-21 12:11
OK, some digging on this shows that there's a regression at the moment in testing this against the current ASP.NET Core. [This issue](https://github.com/aspnet/Extensions/issues/2077) contains more discussion over at the ASP.NET repository. I'm not sure we can support this right now but I'll keep an eye on it for when we can.

**Comment by clairernovotny** [comment] 2021-02-04 23:36
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:36 UTC
Labels: enhancement, external, showstopper, todo :spiral_notepad:
