### ISSUE TITLE
feature: UrlAttribute for parameter

### ISSUE THREAD

**Issue by Paul-N** [reactiveui/refit#1368] opened 2022-05-30 07:59 UTC
**Case**
Let's say we have a REST service and it's response contain a field with url of resource. For example an object that contain a collection and next page url (see https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#981-server-driven-paging). 

**Solution**
It would be nice to have an attribute in REST interface method parameter for setting an url
```
interface IMyService
{
    [Get]
    Task<Response> GetCollectionByUrl([Url] string url);
}
```
You can see same attribute already implemented in Retrofit https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Url.html

**What have I done**
I forked this repo and implemented this attribute support and I wrote one unit test for it. You can check it: https://github.com/Paul-N/refit/tree/feature/url_attribute

**Comment by james-s-tayler** [comment] 2022-07-14 12:00
Nice. Yeah I could see how this makes sense for that particular use case. Though from having added a new attribute to Refit before and it resulting in bugs I highly recommend adding very comprehensive unit test suite to make sure the other attributes still behave properly when they appear in conjunction with the new one. Unfortunately an early design decision in Refit to automagically infer a `[Body]` attribute if none is present on a `POST` request makes this part of the codebase prone to introducing bugs if you're not really careful because of how it tracks how many parameters the method signature has and works out whether or not one of them should be treated like a `[Body]`.

**Comment by hartmark** [comment] 2022-11-10 11:22
This is a working example:

```
    [Put("/{path}")]
    [QueryUriFormat(UriFormat.Unescaped)]
    public Task<string> SendStatusNotificationAsync(string path, StatusNotificationRequest request);

```

Then we need to have the path without the leading / as it will fail otherwise

**Comment by Paul-N** [comment] 2023-05-24 15:33
Any chance this feature will be in ongoing 7.0 version?

**Comment by hansmbakker** [comment] 2024-08-19 14:38
This seems to be a duplicate of #906.

If you agree, can you please close this issue and vote for #906?

**Comment by Paul-N** [comment] 2024-08-20 03:45
This issue is describing slightly different approach for the same problem (original way from Retrofit). Plus I suggested implementation in my fork of this repo. If maintainers decided to use your issue as feature description then no problem, I will close this

**Comment by hansmbakker** [comment] 2024-08-20 07:53
To me, my issue was mostly about the issue I was trying to solve rather than the solution approach - your solution looks good and it's great you made an implementation for it!

I updated my issue with a reference to your solution and asked a maintainer to have a look at it.

**Comment by ChrisPulman** [comment] 2024-09-20 00:01
Closing in favour of #906

**Closed by ChrisPulman** 2024-09-20 00:01 UTC
