### ISSUE TITLE
[BUG] "An error occured deserializing the response" with abstract class

### ISSUE THREAD

**Issue by DirtyNative** [reactiveui/refit#1176] opened 2021-05-16 13:24 UTC
I am defining an interface for Reit which has a get method that returns an abstract model.

``` csharp
public interface IPersonApi
{
	[Get("/email/{email}")]
	Task<Person> GetByEmailAsync(string email);
}
```

``` charp
public abstract class Person
{
	public Guid Id { get; set; }
	...
}
```

``` csharp
public class User : Person
{
	public UserStatus Status { get; set; }
	...
}
```

Now if I make the REST call with Refit, I get the following error:

```
Refit.ApiException: An error occured deserializing the response.
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'UserService.Common.Models.User.Person'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'UserService.Common.Models.User.Person'.
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type type, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue
](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue
](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue
](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T
](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Refit.SystemTextJsonContentSerializer.FromHttpContentAsync[T
](HttpContent content, CancellationToken cancellationToken) in /_/Refit/SystemTextJsonContentSerializer.cs:line 63
   at Refit.RequestBuilderImplementation.DeserializeContentAsync[T
](HttpResponseMessage resp, HttpContent content, CancellationToken cancellationToken) in /_/Refit/RequestBuilderImplementation.cs:line 329
   --- End of inner exception stack trace ---
   at Refit.RequestBuilderImplementation.DeserializeContentAsync[T
](HttpResponseMessage resp, HttpContent content, CancellationToken cancellationToken) in /_/Refit/RequestBuilderImplementation.cs:line 335
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 282
--- End of stack trace from previous location ---
   at ZooPer.Gateway.Repositories.PersonRepository.GetByEmailAsync(String email) in C:\Users\Danie\Documents\Dev\Projects\ZooKeeper\src\Backend\Frameworks\ZooKeeper\ZooPer.Gateway\Repositories\PersonRepository.cs:line 38
   at IdentityService.WebApi.Managers.PersonManager.GetByEmailAsync(String email) in C:\Users\Danie\Documents\Dev\Projects\ZooKeeper\src\Backend\Services\IdentityService\IdentityService.WebApi\Managers\PersonManager.cs:line 21
   at IdentityService.WebApi.Validators.ResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context) in C:\Users\Danie\Documents\Dev\Projects\ZooKeeper\src\Backend\Services\IdentityService\IdentityService.WebApi\Validators\ResourceOwnerPasswordValidator.cs:line 30
   at IdentityServer4.Validation.TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at ZooPer.Common.Middleware.ZooKeeperExceptionHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Users\Danie\Documents\Dev\Projects\ZooKeeper\src\Backend\Frameworks\ZooKeeper\ZooKeeper.Common\Middleware\ZooKeeperExceptionHandlerMiddleware.cs:line 27
```

I am using ASP .Net 5 and the latest release of Refit.

Also I tried to use a custom converter and external libs, but all resulting in the same exception

Let me know if you need more information

**Comment by unleashed-jamest** [comment] 2021-05-17 02:31
@DirtyNative I simply don't think you can do what you're trying to do. An abstract class can't be instantiated, so no matter which serializer you use it's going to throw the same exception. Essentially what you're asking the computer to do is take a string and turn it into an object, and to do that it's going to some point have to call `new Person`, and an `abstract` class by definition doesn't have all its behavior defined, so that will throw an exception. 

It should work perfectly fine if you return `Task<User>` and not `Task<Person>`

**Comment by DirtyNative** [comment] 2021-05-17 08:17
@unleashed-jamest Well yes that is true, but this is what converters are built for. I managed to get it to work rudimentally with a PersonConverter, but with this, i stumbled over another thing: It seems that Refit does not use the default JsonOptions. I have to define my own within the Converter. Is this intended or maybe a bug?

**Comment by james-s-tayler** [comment] 2021-05-17 08:37
Ah, I see. So it works if you define a converter and add it to the JSON serialization settings kind of like this https://blog.codeinside.eu/2015/03/30/json-dotnet-deserialize-to-abstract-class-or-interface/ ? 

Are you able to show what you had to do to get it working?

**Comment by DirtyNative** [comment] 2021-05-17 08:56
Exactly, i know those converters from other languages and frameworks and they are not that different. Anyway, here is the code:

``` csharp
public class PersonConverter : JsonConverter<Person>
{
	public override Person Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		if (!JsonDocument.TryParseValue(ref reader, out var doc))
		{
			throw new JsonException("Failed to parse JsonDocument");
		}

		if (!doc.RootElement.TryGetProperty("$type", out var type))
		{
			throw new JsonException("Failed to extract type property, it might be missing?");
		}

		var typeValue = type.GetString();
		var rootElement = doc.RootElement.GetRawText();

		return typeValue switch
		{
			nameof(User) => JsonSerializer.Deserialize<User>(rootElement, new JsonSerializerOptions()
			{
				PropertyNamingPolicy = JsonNamingPolicy.CamelCase
			}),
			nameof(Administrator) => JsonSerializer.Deserialize<Administrator>(rootElement,
				new JsonSerializerOptions()
				{
					PropertyNamingPolicy = JsonNamingPolicy.CamelCase
				}),
			_ => throw new JsonException($"{typeValue} has not been mapped to a custom type yet!")
		};
	}
	public override void Write(Utf8JsonWriter writer, Person value, JsonSerializerOptions options)
	{
		throw new NotImplementedException();
	}
}
```

As you can see, I have to define the `JsonSerializerOptions`, especially `JsonNamingPolicy` directly in order to get the deserialization to work. If I only define that inside my startup.cs, it will fail to deserialize (all values are default).

``` charp
services.AddControllers()
	.AddJsonOptions(options =>
	{
		options.JsonSerializerOptions.Converters.Add(new PersonConverter());
		options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
		options.JsonSerializerOptions.SetupExtensions();
		options.JsonSerializerOptions.GetDiscriminatorConventionRegistry().DiscriminatorPolicy =
			DiscriminatorPolicy.Always;
	});
```

**Comment by james-s-tayler** [comment] 2021-05-17 09:45
Are you using `Newtonsoft.Json` or `System.Text.Json`? The docs say that at least for `Newtonsoft.Json` it should up the settings on `Newtonsoft.Json.JsonConvert.DefaultSettings`, but it doesn't make any mention of if that's supported for `System.Text.Json`.

Does it work if you define those things on `RefitSettings` instead? 

   
Below is the code that instantiates the NewtonsoftJsonContentSerializer, so you can see expected behavior here.

        public NewtonsoftJsonContentSerializer(JsonSerializerSettings? jsonSerializerSettings)
        {
            this.jsonSerializerSettings = new Lazy<JsonSerializerSettings>(() => jsonSerializerSettings
                                                                                 ?? JsonConvert.DefaultSettings?.Invoke()
                                                                                 ?? new JsonSerializerSettings());
        }

And here is the code that instantiates the `SystemTextJsonContentSerializer` 

        /// <summary>
        /// Creates a new <see cref="SystemTextJsonContentSerializer"/> instance
        /// </summary>
        public SystemTextJsonContentSerializer() : this(new JsonSerializerOptions())
        {

            // Set some defaults
            // Default to case insensitive property name matching as that's likely the behavior most users expect
            jsonSerializerOptions.PropertyNameCaseInsensitive = true;
            jsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            jsonSerializerOptions.Converters.Add(new ObjectToInferredTypesConverter());
            jsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
        }

        /// <summary>
        /// Creates a new <see cref="SystemTextJsonContentSerializer"/> instance with the specified parameters
        /// </summary>
        /// <param name="jsonSerializerOptions">The serialization options to use for the current instance</param>
        public SystemTextJsonContentSerializer(JsonSerializerOptions jsonSerializerOptions)
        {
            this.jsonSerializerOptions = jsonSerializerOptions;
        }

The `System.Text.Json` one does appear to have an opinion of it's own if not explicitly provided one.

**Comment by DirtyNative** [comment] 2021-05-17 10:15
I am using the System.Text.Json namespace.
How do I use the SystemTextJsonContentSerializer?

**Comment by unleashed-jamest** [comment] 2021-05-17 10:43
If you show me how you're constructing the Refit client that would help. Either you're doing it via DI using HttpClientFactory or you're doing it via `RestService.For<T>`, in either case it's possible to supply a `RefitSettings` object. That object allows you to control which serialization library you use. If you don't supply any `RefitSettings` it'll just new one up on your behalf which will by default use the `SystemTextJsonContentSerializer` which will call that opinionated constructor. Check the docs, but you should be able to pass in custom settings to `SystemTextJsonContentSerializer` that way.

**Comment by DirtyNative** [comment] 2021-05-17 11:27
I am registering the RefitClient via `AddRefitClient`:

``` csharp
services.AddRefitClient<IPersonApi>().ConfigureHttpClient(c => c.BaseAddress = new Uri("the Uri"));
```

With this, I can inject the IPersonApi where I need to use it.

**Comment by unleashed-jamest** [comment] 2021-05-17 12:31
So you should be able to do like:

    var refitSettings = new RefitSettings 
    {
       //custom config here
    };
    services.AddRefitClient<IPersonApi>(refitSettings).ConfigureHttpClient(c => c.BaseAddress = new Uri("the Uri"));

**Comment by DirtyNative** [comment] 2021-05-17 13:24
Okay I see, I misunderstood your anwer. After implementing my custom RefitSettings, the converter also receives the correct JsonOptions.

But this leads me to the following question: Doesn't refit use the Default Json settings?

**Comment by unleashed-jamest** [comment] 2021-05-17 21:21
The code snippets I posted show the constructors of both `NewtonsoftJsonContentSerializer` and `SystemTextJsonContentSerializer` , and from reading that code the answer to your question appears to be that in the case of `Newtonsoft.Json` it can/will use the default settings, but in the case of `System.Text.Json` it appears not to, and rather has it's own opinion on what settings should be used.

If it's possible to use the default Json settings in the case of `System.Text.Json` also then it looks like that'd be a good change to make here.

**Comment by clairernovotny** [comment] 2021-06-17 11:51
Closing due to age. Please reopen if there's still an issue.

**Closed by clairernovotny** 2021-06-17 11:51 UTC
Labels: bug
