### ISSUE TITLE
[BUG] Inherited interface multiple issues

### ISSUE THREAD

**Issue by kirill-zhukov** [reactiveui/refit#931] opened 2020-05-26 11:59 UTC
**Describe the bug**
Inherited interface has multiple issues:
For example overloaded functions are not supported
Attributes that contains string concat causes "does not seem to be refit interface" error
Probably there are other issues.

**Steps To Reproduce**
The following code will cause build error:
CS0535	'AutoGeneratedITest' does not implement interface member 'ICRUD<TestData>.Read()'	...\obj\Debug\netcoreapp3.1\RefitStubs.g.cs	102	N/A

 ```
    public class TestData
    {
        public string Name { get; set; }
    }

    public interface ICRUD<T>
    {
        [Post("/read")]
        Task<T> Read(long start, long limit);

        [Post("/read")]
        Task<T> Read(); 
    }
    
    public interface ITest : ICRUD<TestData>
    {
        
    }

    class Program
    {
        static async void run()
        {
            var client = RestService.For<ITest>("http://localhost:5000/test");
            var result = await client.Read(0, 0);
            Console.WriteLine("OK");
        }

        static void Main(string[] args)
        {
            run();
        }
    }
```

or if you remove overloaded methods set attribute like     [Post("/" + "read")] in first (important) method of the interface there will be a runtime exception:
Interface does not seem to be a correct refit interface

If we utilize the interface without inheritence everything works correctly:
 `var client = RestService.For<ICRUD<TestData>>("http://localhost:5000/test");
`
**Expected behavior**

Inherited interface should work exactly in the way the base interface works

**Environment**

- OS:       Windows 10 Pro
- Version:   5.1.67
- Working Version: N/A

**Comment by kirill-zhukov** [comment] 2020-05-26 12:36
Another thing found is that if both interfaces were declared in another assembly from the place where the client is created, there's always exception that the interface is not correct refit, doesn't matter what methods does it have.
So it looks like that the whole interface inheritance functionality works wrong right now.

**Comment by jamiehowarth0** [comment] 2020-06-18 00:15
@kirill-zhukov we're very much aware of issues with interfaces not working when referenced from other projects - this is because at build-time, Refit only currently processes the project it's referenced in, and only processes the interfaces containing a "using Refit;" statement, and therefore doesn't support complex nesting/separate referencing. This is a known issue and I believe @anaisbetts / @clairernovotny have been looking at using alternative methods to improve how this is done in future (see #775). Closing as technically a duplicate of that ticket.

**Closed by jamiehowarth0** 2020-06-18 00:15 UTC
Labels: bug
