### ISSUE TITLE
Json Post Passing Null

### ISSUE THREAD

**Issue by napalm684** [reactiveui/refit#384] opened 2017-10-31 13:44 UTC
I am not sure if this is related to the 4.x bug around content length being 0 or not (as it definitely is in the api project I am calling from Refit) but the parameters recieved by the api are null in ASP.Net WebApi (full framework, not core).

Api Method Example
```
        [HttpPost]
        [Route("posttest")]
        public int PostTest(Test test)
        {
            return 1;
        }
```

Refit Interface
```
    public interface IPostTestService
    {
        [Post("/posttest")]
        Task<int> PostTest([Body] Test value);
    }
```

Downgrading to 3.1.0 from 4.0.1 fixed the problem.  The only other noteable is I am using NTLM authentication via the following helper class found in your repo's issues:

```
    internal class WindowsAuthenticationRefitSettings : RefitSettings
    {
        public WindowsAuthenticationRefitSettings()
        {
            SetCredentials(CredentialCache.DefaultCredentials);
        }

        public WindowsAuthenticationRefitSettings(string username, string password)
        {
            SetCredentials(new NetworkCredential(username, password));
        }

        public WindowsAuthenticationRefitSettings(string username, string password, string domain)
        {
            SetCredentials(new NetworkCredential(username, password, domain));
        }

        public WindowsAuthenticationRefitSettings(ICredentials credentials)
        {
            SetCredentials(credentials);
        }

        private void SetCredentials(ICredentials credentials)
        {
            HttpMessageHandlerFactory = () => new HttpClientHandler() { Credentials = credentials };
        }
    }
```

**Comment by Cheesebaron** [comment] 2017-10-31 18:14
Are you implying it works without the NTLM authentication?

**Comment by napalm684** [comment] 2017-11-01 11:16
No I am not implying that.  I don't think security is the issue here given I hit the endpoint just fine with both versions of Refit in question.  The difference is in 3.1.0 I actually get the posted content from the body.  In 4.0.1 I do not.

**Comment by Cheesebaron** [comment] 2017-11-01 15:51
I can't reproduce it sending a Post from iOS. Do you have more details?

**Comment by napalm684** [comment] 2017-11-02 01:35
@Cheesebaron I will try to get a repro together.

**Comment by Cheesebaron** [comment] 2017-11-02 08:23
What I tried:

Created a new ASP.NET Web API project. Added a controller which took a class `Test` as argument. Something like:

```csharp
public class HelloController : ApiController 
{
    [HttpPost]
    public void Post(Test test)
    { // breakpoint here
    }
}
```

In the iOS app I did:

```csharp
public interface IApi
{
    [Post("/api/hello")]
    Task PostStuff(Test test);
}
```

Then calling it like:

```csharp
var api = RestService.For<IApi>("http://127.0.0.1:8080");
await api.PostStuff(new Test { Hello = "Hello" });
```

Works like a charm. I get the correct value in the controller.

**Comment by ZOXEXIVO** [comment] 2017-11-16 15:41
Same issue in 4.0.1
Downgraded

**Comment by Cheesebaron** [comment] 2017-11-16 20:05
@ZOXEXIVO if you can provide a repro we are happy to look into the issue.

**Comment by ZOXEXIVO** [comment] 2017-11-16 20:24
@Cheesebaron In your example, you need to do some changes:
We use Owin ApiControllers (some legacy code) and have code likes this:
Use [FromBody] attribute

```
public class HelloController : ApiController 
{
    [HttpPost]
    public void Post([FromBody]Test test)
    { 
         //test null at in 4.0.1 
    }
}
```

**Comment by ryanbuening** [comment] 2017-11-22 14:27
Is this issue related?: https://github.com/paulcbetts/refit/issues/372

**Comment by bennor** [comment] 2018-01-26 21:36
If the issue is related to the missing `Content-Length` header, you can [fix it using version 4.1.0](https://github.com/paulcbetts/refit#buffering-and-the-content-length-header).

**Comment by napalm684** [comment] 2018-02-14 03:27
I will have to try and test this when I get a chance.  We held our version at 3.1.0. because of the problem.  Strange it was only happening for us in full framework.

**Comment by armandelta2002** [comment] 2019-08-02 09:33
before send class convert to string and add one " fist string and add one " on last string then send body
sample code is :
```
   WebPageModel webPageModelSave = new WebPageModel();
                webPageModelSave = ObjectCopier.CloneClass(Public.CashEntity.webPageModel);
                webPageModelSave.Address = uxLabel_AddressTitle.Text;

                string codeingData = JsonConvert.SerializeObject(webPageModelSave);
               codeingData = ArmanSerialize.CryptoString.Encrypt(codeingData, "5552552");
                string resutlt = await Public.Helper.ApiServer.PutWebPage("123", "\""+codeingData+"\"");
```
and on server remove the " fist and last string like this:
 ```
// PUT api/<controller>/5
        [HttpPut("{id}/")]
        public string Put(string id, [FromBody]string value)
        {
            string removeCotation = value.Remove(value.Length - 1, 1).Remove(0, 1);

            string valueItem = ArmanSerialize.CryptoString.Decrypt(value, "5552552");
            string baseUrl = Request.Host.Host;
            baseUrl = baseUrl.ToLower().Replace("http://", "").Replace("https://", "");
            var serverID = 123;
            if (id.Replace("\"", "") == serverID.Replace("\"","") && !string.IsNullOrEmpty(valueItem))
            {
                WebPageModel webPageModel = new WebPageModel();
                webPageModel = JsonConvert.DeserializeObject<WebPageModel>(valueItem);
                EntityFrameworkCore.LogicLayer logicLayer = new EntityFrameworkCore.LogicLayer();
                logicLayer.UpdateWebPageModel(webPageModel);
                return JsonConvert.SerializeObject("OK");
            }
            else
            {
                //error
                return JsonConvert.SerializeObject("Error");
            }
        }
```

**Comment by clairernovotny** [comment] 2021-02-04 23:48
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:48 UTC

**Comment by pellesantiago** [comment] 2021-08-04 12:01
> Closing due to age. Please try Refit v6 and reopen if still an issue.

Having the same problem with V6...
I solved it when I changed the default serializer to newtonsoft.
