### ISSUE TITLE
[BUG] Content-Type header does not apply

### ISSUE THREAD

**Issue by vivekse** [reactiveui/refit#672] opened 2019-06-07 17:54 UTC
```
[Headers("Content-Type: application/json")]
public interface IApi
{
    [Post("/users")]
    Task<User> CreateUser(string name, string job);
}
```
Header "Content-Type: application/json" is not applied to request in above sample

**Comment by bennor** [comment] 2019-06-08 10:46
I can't reproduce this in a console app using the [httpbin.org post API](https://httpbin.org/#/HTTP_Methods/post_post).

```csharp
class Program
{
    static async Task Main(string[] args)
    {
        var httpBin = RestService.For<IHttpBinApi>("https://httpbin.org");
        var response = await httpBin.Post("some-name", "some-job");
        Console.WriteLine(response);
    }
}

[Headers("Content-Type: application/json")]
public interface IHttpBinApi
{
    [Post("/post")]
    Task<string> Post(string name, string job);
}
```

Gives this output (the httpbin API in question responds with information about the _request_ it received): 

```json
{
  "args": {
    "job": "some-job",
    "name": "some-name"
  },
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Content-Length": "0",
    "Content-Type": "application/json",
    "Host": "httpbin.org"
  },
  "json": null,
  "origin": "<removed>",
  "url": "https://httpbin.org/post?name=some-name&job=some-job"
}
```

We also have [a test for this exact thing](https://github.com/reactiveui/refit/blob/a1bfe49ff616c26823d1cad79130f9164a90b778/Refit.Tests/RequestBuilder.cs#L1066), so I'm pretty confident it works. 

I'm going to close this, but feel free to reopen if you can prove it somehow. Would be amazing if you could add a test that shows the bug in action.

**Closed by bennor** 2019-06-08 10:46 UTC
Labels: bug
