### ISSUE TITLE
[BUG] Wrong method called when Refit interface has duplicate names.

### ISSUE THREAD

**Issue by ashleyemery** [reactiveui/refit#661] opened 2019-05-08 09:38 UTC
**Describe the bug**
Recently I was using Refit to call a controller with two Patch methods.  The methods had identical names but included different JsonPatchDocument types.  

```
                [Patch("/students?email={email}&apikey={apikey}")]
		Task<Student> PatchAsync(string email, JsonPatchDocument<Student> studentPatch, string apiKey);

		[Patch("/students/studentinfo?email={email}&apikey={apikey}")]
		Task<StudentInfo> PatchAsync(string email, JsonPatchDocument<StudentInfo> studentInfoPatch, string apiKey);

```
The behaviour I observed was that if the first method in the interface was called, Refit correctly called the Patch Student method on the controller.  However if I then called the second method it again called the Patch Student method on the controller (and of course failed on the controller because the patched property didn't exist on the Student class).  If I called the second method first followed by the first then the Patch StudentInfo method on the controller was called twice.

It's as if Refit is caching the controller path based on the method name alone.  

**Steps To Reproduce**
Using a Refit API with two Patch methods with identical names and parameters only differing by JsonPatchDocument type, call one method followed by the other using the same instance of the Refit API. The controller method matching the first API method called will be called twice.

**Expected behavior**
I expected the each method to call its corresponding controller method using the API path specified.

**Environment**
- OS:       Windows
- Version   10
- Device:   IBM ThinkPad
The problem also occurred in a docker container deployed on AWS.

**Comment by ashleyemery** [comment] 2019-05-10 14:47
I did some further testing and can confirm that the bug does not occur if the identically named methods have different numbers of parameters or if one of the JsonPatchDocument parameters is replaced with a completely different type of class.  I think it must be to do with the method signatures being cached without reference to the type included in the generic JsonPatchDocument.

**Comment by benjaminhowarth1** [comment] 2019-06-08 13:21
I'll try and write a unit test to reproduce this.

**Comment by clairernovotny** [comment] 2021-02-04 23:30
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:30 UTC
Labels: bug
