### ISSUE TITLE
[QueryParameters] Are broken for classes with IEnumerable properties

### ISSUE THREAD

**Issue by ahmedalejo** [reactiveui/refit#587] opened 2018-12-04 14:45 UTC
### THE FAILING SPECIFICATION
>### _Given_ `the following class definition`
>>```csharp
>>public class PostQueryOptions
>>{
>>      public PostQueryOptions()
>>      {
>>           KeywordIds = new int[0];
>>           MaxResults = 100;
>>      }
>>
>>      [DataMember("tags")]
>>      public int[] KeywordIds { get; set; }
>>
>>      [DataMember("limit")]
>>      public int MaxResults { get; set; }
>>
>>      public string SearchPhrase { get; set; }
>>}
>>```
>### _And_ `the following Refit interface definition`
>>```csharp
>>public interface INewsFeedClient
>>{
>>      [Get("api/posts")]
>>      Task<ObservableCollection<PostDTO>> GetNotesAsync(
>>             PostQueryOptions options, 
>>             CancellationToken token = default);
>>}
>>```
>### _When_ `the following request is made `
>>```csharp
>>GetNotesAsync(new PostQueryOptions 
>>{ 
>>     KeywordIds  = new [] { 1, 2 },
>>     MaxResults = 10,
>>     SearchPhrase = "play station"
>>})
>>```
>### Then `the following url should be generated: `
>> `GET` [api/posts?tags=1&tags=2&limit=10&SearchPrase=play+station]()
>
>### _But_ instead generates the following:
>>  `GET` [api/posts?KeywordIds=System.Int32%5B%5D&MaxResults=10&SearchPrase=play+station']() 

### Proposal
Add a method overload to  `IUrlParameterFormatter` 
That allows passing the propertyName
```csharp
public interface IUrlParameterFormatter
{
    ...
    string Format(object value, string propertyName, ParameterInfo parameterInfo);
//or
    string Format(object value, ParameterInfo parameterInfo, string propertyName = null);
}
```
Allowing the following customization:
```csharp
    public class CustomUrlParameterFormatter : DefaultUrlParameterFormatter
    {
        public override string Format(object parameterValue, string propertyName, ParameterInfo parameterInfo)
        {
            if (parameterValue is IEnumerable enumerable)
            {
                var result = ToQueryString(enumerable, parameterName: propertyName);
                return result;
            }

            return UrlHelpers.ToString(parameterValue);
        }

        public static string ToQueryString(IEnumerable query, string parameterName)
        {
            var values = query.Cast<object>().Select(ToString).ToArray();
            var separator = parameterName + "=";

            return values.Any() ? separator + string.Join("&" + separator, values) : "";
        }

        public static string ToString(object value)
        {
            var json = JsonConvert.SerializeObject(value).Replace("\\\"", "\"").Trim('"');

            return Uri.EscapeUriString(json);
        }
    }
```

Which was previously possible by using `parameterInfo.Name` as follows:
```csharp
var result = ToQueryString(enumerable, parameterName: parameterInfo.Name);
```

### Current State
Un-aware of a possible work around for the time  being.

I´m aware that my proposal is a breaking change, but it already breaks(silently at least for my use case) so i guess we should fix this.

**Obs:** We should consider using newtonsoft for query parameter serialization to empower robust scenarios e.g supporting `[IgnoreDataMember]`, `[DataMember("phrase")]` and `[DataMember(Order=2)]` instead of (only) `Alias` .

**Comment by ahmedalejo** [comment] 2018-12-14 11:48
Any thoughts on this guys?
It be grate have your opinions

**Comment by ahmedalejo** [comment] 2019-02-11 11:24
In case any one hits this issue I will be making an attempt of providing a pull request by April, yes April, That’s when I’ll be updating my apps in the store

Thanks for the feedback guys

**Comment by ajshiff** [comment] 2019-08-16 19:14
Hi @ahmedalejo .

There is a work around for this issue, but it is not clear or apparent. However, I am happy to say it is simple, and worked for me quite nicely. 

Simply make the type contained in the enumerable, nullable. I believe this works because it turns the type (int, bool, enum, etc) into an object. 

So your query params class would look like this: (note the `?` in the `int?[]`)

```c#
public class PostQueryOptions
{
     public PostQueryOptions()
     {
          KeywordIds = new int?[0];
          MaxResults = 100;
     }

     [DataMember("tags")]
     public int?[] KeywordIds { get; set; }

     [DataMember("limit")]
     public int MaxResults { get; set; }

     public string SearchPhrase { get; set; }
}
```

I was inspired to attempt this work around when poking around RequestBuilderImplementation.cs and read lines 609-640, as linked below. 
https://github.com/reactiveui/refit/blob/master/Refit/RequestBuilderImplementation.cs#L609-L640

On line 627 it uses the `as` keyword to try to cast the type to an `IEnumerable<object>`. It will loop through the Enumerable if it is successful (not null). I haven't hand verified that this is the exact line that is causing the enumerable to serialize as `System.Int32%5B%5D&MaxResults=10&SearchPrase=play+station`, but it at least inspired this work around. 

I'll clone the repo and test whether it is these exact lines that aren't catching enumerables of types for correct formatting, and get back to this thread when I have more information.

**Comment by benjaminhowarth1** [comment] 2019-08-20 10:39
This should've been fixed in a patch I submitted a few months ago, but Refit hasn't had a public Nuget release since then. You are welcome to use Myget to install 4.7.20, which should contain the necessary fix to handle this scenario.

**Comment by benjaminhowarth1** [comment] 2019-08-21 10:35
The latest Refit has been released to Nuget as 4.7.51, please update to this and let us know if you can still reproduce the problem.

**Comment by ajshiff** [comment] 2019-08-21 19:09
@benjaminhowarth1 Thanks for your contribution so far.

I have updated to version 4.7.51, and successfully recreated the bug under the same conditions. 

I have uploaded the code used to reproduce the bug using Refit v4.7.51, to the link below:
https://github.com/ajshiff/refit-ienumerable-query-bug

To reproduce the bug, the IEnumerable\<T\> must be a property or field within a container class, and \<T\> must be a [built-in-type](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/built-in-types-table) or an [enum](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/enum).

**Comment by meeple142** [comment] 2019-08-21 20:25
First I want to thank everyone for the awesome package!
I want to add my demo of the same bug that @ajshiff  is talking about.
I add the `[Query(CollectionFormat.Multi)]` attribute to see if that helps.  Also I am using an array of `int`s not a `list` in my query object.

Take a look at [program.cs](https://github.com/meeple142/refit-query-bug/blob/master/RefitBug/Program.cs)

[whole repo](https://github.com/meeple142/refit-query-bug)
Maybe we are just doing something wrong?
Thank you for your help!!

**Comment by benjaminhowarth1** [comment] 2019-08-28 16:31
@meeple142 OK, I think I know why, it's cause when we determined property types on POCOs for [Query] types, we simply call ToString(). We can extend IEnumerable support, but for any nested complex types, we'll update the documentation to insist you override ToString on the top-level POCO to handle your own serialization.

**Comment by benjaminhowarth1** [comment] 2019-08-28 16:57
@meeple142 @ajshiff big thanks to both of you for reproducible test cases, I'll take a look at these today.

**Comment by ahmedalejo** [comment] 2019-08-29 19:39
@ajshiff great find. That didn´t cross my mind!
```csharp
[DataMember("tags")]
public int?[] KeywordIds { get; set; }
```

**Closed** 2020-03-22 13:30 UTC

**Comment by meeple142** [comment] 2020-04-12 13:52
Thank you!!
