### ISSUE TITLE
System.InvalidOperationException: IFuelEconomy doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project

### ISSUE THREAD

**Issue by luthier8741** [reactiveui/refit#202] opened 2015-11-08 02:05 UTC
## Using Xamarin Studio 5.9.8 on OSX El Capitain, I am having a problem in both Xamarin Android and Xamarin iOS.

I am generating the api using this:

try 
                {
                    if (_api == null)
                    {
                        _api = RestService.For<IFuelEconomy>(FUELECONOMY_URL);
                    }

```
                return _api;
            }
            catch(Exception ex)
            {
                var e = ex;
            }

            return null;
```

---

My IFuelEconomy Interface looks like this:

public interface IFuelEconomy
    {
        [Get("/ws/rest/vehicle/menu/year")]
        Task<List<ModelYear>> GetModelYears();

```
    [Get("/ws/rest/vehicle/menu/make")]
    Task<List<VehicleMake>> GetVehicleMakers(string year);

    [Get("/ws/rest/vehicle/menu/model")]
    Task<List<VehicleModel>> GetVehicleModels(string year, string make);

    [Get("/ws/rest/vehicle/menu/options")]
    Task<List<VehicleModelOption>> GetVehicleModelOptions(string year, string make, string model);

    [Get("/ws/rest/vehicle/{vehicleId}")]
    Task<VehicleRecord> GetVehicleRecord(string vehicleId);

    [Get("/ws/rest/fuelprices")]
    Task<FuelPrices> GetFuelPrices();

}
```

---

Keep getting this exception:
ex  {System.InvalidOperationException: IFuelEconomy doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.   at Refit.RestService.For[IFuelEconomy](System.Net.Http.HttpClient client, Refit.RefitSettings settings) [0x00074] in /Users/matt/Downloads/paulcbetts-refit-4ec12ca/Refit/RestService.cs:33    at Refit.RestService.For[IFuelEconomy](System.String hostUrl, Refit.RefitSettings settings) [0x00058] in /Users/matt/Downloads/paulcbetts-refit-4ec12ca/Refit/RestService.cs:63    at Refit.RestService.For[IFuelEconomy](System.String hostUrl) [0x00000] in /Users/matt/Downloads/paulcbetts-refit-4ec12ca/Refit/RestService.cs:70    at com.mperkins.fueleconomy.FuelEconomyWebManager.get_api () [0x00014] in /Users/matt/Projects/FuelEconomy/App_Android_FuelEconomy/FuelEconomyWebManager.cs:23 }    System.InvalidOperationException

**Comment by AlexandruGH** [comment] 2018-01-25 16:12
Greetings sir, did you managed to solve the problem?
I have a similar error with newer versions of VS and refit.
Thanks in advance!

**Comment by Cheesebaron** [comment] 2018-01-25 16:32
@AlexandruGH please stop vamping old issues. If you have an issue, please create a new one.

**Comment by bennor** [comment] 2019-06-11 03:25
Closing because it's 4 years old, a probable duplicate of a few other issues and hasn't been followed up.

**Closed by bennor** 2019-06-11 03:25 UTC
