### ISSUE TITLE
How to handle Newtonsoft.Json.JsonReaderException expecting JSON receiving HTML

### ISSUE THREAD

**Issue by jthegeman** [reactiveui/refit#966] opened 2020-08-24 16:16 UTC
I am receiving an error when calling an API and it returns HTML(error occured) instead of JSON which causes the Xamarin app to crash. I realize this is not ideal for the API to return this, but what I am working with.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Task<ApiResponse<ContentModel>> GetContentModel();

**Comment by jthegeman** [comment] 2020-09-08 16:51
While waiting for this bug to be fixes, Does anyone know how to handle this gracefully? It crashes in iOS.

**Comment by jamiehowarth0** [comment] 2020-09-09 14:07
Can you wrap your calling code into a try/catch block?

**Comment by jthegeman** [comment] 2020-09-17 15:51
It fails at, and I did try to wrap the calls.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0004a] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize[T] (Newtonsoft.Json.JsonReader reader) [0x00000] in <2073514815234917a5e8f91b0b239405>:0 
  at Refit.NewtonsoftJsonContentSerializer.DeserializeAsync[T] (System.Net.Http.HttpContent content) [0x000a6] in /_/Refit/NewtonsoftJsonContentSerializer.cs:53 
  at Refit.RequestBuilderImplementation.DeserializeContentAsync[T] (System.Net.Http.HttpResponseMessage resp, System.Net.Http.HttpContent content) [0x0028e] in /_/Refit/RequestBuilderImplementation.cs:314 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x002a3] in /_/Refit/RequestBuilderImplementation.cs:258

**Comment by jamiehowarth0** [comment] 2020-10-01 20:38
@jthegeman I have a hunch that this may be resolved by #953 which should populate the Content property with HTML. Might be best to try a nightly/your own build locally with this change in?

**Comment by jthegeman** [comment] 2020-10-01 20:45
@jamiehowarth0 I hesitated in asking, but still somewhat new to Xamarin, how do you pull down nightly nuget packages? Is it in the prerelease section?

I could easily do this in gradle or cocoapods. :(

**Comment by jamiehowarth0** [comment] 2020-10-01 21:12
If this is in Xamarin, what are you using for an IDE? You basically need to tell your IDE and/or Nuget to point to the nightly feed that auto-builds Refit in between initial releases, which is found at `https://pkgs.dev.azure.com/dotnet/ReactiveUI/_packaging/Refit/nuget/v3/index.json`. Once you've added that, you update your Refit dependency to a nightly.

**Comment by jthegeman** [comment] 2020-10-01 21:21
@jamiehowarth0 Thank you, I am using Rider and VS for Mac.

**Comment by jamiehowarth0** [comment] 2020-10-01 21:32
@jthegeman [try this](https://www.jetbrains.com/help/rider/Using_NuGet.html#sources)

**Comment by jamiehowarth0** [comment] 2020-10-02 13:31
@jthegeman how'd you get on with that?

**Comment by jamiehowarth0** [comment] 2020-10-09 16:27
@jthegeman any progress? If so, I'll close this issue, otherwise I'll try and get a test case together.

**Comment by jthegeman** [comment] 2020-10-11 14:50
I have a deadline of EOD Monday, that I am not able to test. I will test Tuesday!
When will the be released to the release nuget?

**Comment by jthegeman** [comment] 2020-10-15 18:51
@jamiehowarth0 should this be fixed in 5.2.1 or do I still need to put the latest nightly build?

Just FYI I am using 5.2.1 and still getting 

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0004a] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2073514815234917a5e8f91b0b239405>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize[T] (Newtonsoft.Json.JsonReader reader) [0x00000] in <2073514815234917a5e8f91b0b239405>:0 
  at Refit.NewtonsoftJsonContentSerializer.DeserializeAsync[T] (System.Net.Http.HttpContent content) [0x000a6] in /_/Refit/NewtonsoftJsonContentSerializer.cs:53 
  at Refit.RequestBuilderImplementation.DeserializeContentAsync[T] (System.Net.Http.HttpResponseMessage resp, System.Net.Http.HttpContent content) [0x0028e] in /_/Refit/RequestBuilderImplementation.cs:314 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x002a3] in /_/Refit/RequestBuilderImplementation.cs:258

**Comment by rasidr** [comment] 2020-11-23 10:06
I am experiencing the same in in version `5.2.1` and `6.0.0-preview.9`:

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Refit.NewtonsoftJsonContentSerializer.DeserializeAsync[T](HttpContent content) in /_/Refit/NewtonsoftJsonContentSerializer.cs:line 53
   at Refit.RequestBuilderImplementation.DeserializeContentAsync[T](HttpResponseMessage resp, HttpContent content) in /_/Refit/RequestBuilderImplementation.cs:line 315
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 259
```

It would be great if I can get an ApiResponse/ApiException to inspect status code and/or content.

**Comment by Rob-Houweling** [comment] 2020-12-08 13:33
Hi,

Love the library ;) However, I am experiencing the same issue as the people above and I'm finding it very difficult to debug these kind of errors. I have wrapped it in a try-catch block but it only catches the generic Exception which does, obviously, not contain any useful info for resolving this issue.

```
try
{
    return await _generatedProxy.GetDashboardModelAsync();
}
catch (ValidationApiException validationException)
{
}
catch (ApiException exception)
{
    // other exception handling
}
catch(Exception ex)
{
}
```

Like @rasidr suggests, please return an ApiException with the json response included so we can debug these types of issues.

**Comment by clairernovotny** [comment] 2020-12-08 14:56
Is there an example of a failing test case? I agree that this should be in the `ApiException` with the `InnerException` set to the original.

**Comment by Rassi** [comment] 2020-12-09 08:52
> Is there an example of a failing test case? I agree that this should be in the `ApiException` with the `InnerException` set to the original.

There are no current tests showing this issue. I have tried creating a test (in `Refit.Tests.ResponseTests`) which looks like it gives me the same call stack:
```csharp
        [Fact]
        public async Task WithNonJsonResponse_ShouldReturnApiException()
        {
            const string nonJsonResponse = "bad response";
            var expectedResponse = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(nonJsonResponse)
            };
            expectedResponse.Content.Headers.Clear();

            mockHandler.Expect(HttpMethod.Get, "http://api/aliasTest")
                       .Respond(req => expectedResponse);

            var actualException = await Assert.ThrowsAsync<ApiException>(() => fixture.GetTestObject());

            Assert.NotNull(actualException.Content);
            Assert.Equal(nonJsonResponse, actualException.Content);
        }
```

**Comment by Rob-Houweling** [comment] 2020-12-09 08:58
Hi Claire,

Just tried and retrieving any corrupt JSON from a webservice using refit will do the trick. I don't have a reproduction project available at the moment.
@Rassi could you change the test so that the response is html code? The error states that the error occurs when parsing <

**Comment by Rassi** [comment] 2020-12-09 09:10
> @Rassi could you change the test so that the response is html code? The error states that the error occurs when parsing <

Sure. I was trying to make a more general test, since it is the same call stack whether it is html or anything non-json:

```csharp
        [Fact]
        public async Task WithHtmlResponse_ShouldReturnApiException()
        {
            const string htmlResponse = "<html><body>Hello world</body></html>";
            var expectedResponse = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(htmlResponse)
            };
            expectedResponse.Content.Headers.Clear();

            mockHandler.Expect(HttpMethod.Get, "http://api/aliasTest")
                       .Respond(req => expectedResponse);

            var actualException = await Assert.ThrowsAsync<ApiException>(() => fixture.GetTestObject());

            Assert.NotNull(actualException.Content);
            Assert.Equal(htmlResponse, actualException.Content);
        }
```

**Comment by Rob-Houweling** [comment] 2020-12-09 09:14
Just verified what my response value was: "SpotYou.Shared.Models.DashboardModel". I accidentally created a "normal" MVC controller instead of a ApiController so it returned the typename of the return class. I think the parseValue method fails on the "." and therefore isn't failing with your testcase @Rassi

**Comment by Rassi** [comment] 2020-12-09 09:22
> Just verified what my response value was: "SpotYou.Shared.Models.DashboardModel". I accidentally created a "normal" MVC controller instead of a ApiController so it returned the typename of the return class. I think the parseValue method fails on the "." and therefore isn't failing with your testcase @Rassi
Using your response value in my test I get the following:
```
Xunit.Sdk.ThrowsException
Assert.Throws() Failure
Expected: typeof(Refit.ApiException)
Actual:   typeof(System.Text.Json.JsonException): 'S' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadValueCore[TValue](JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader& reader, JsonSerializerOptions options)
   at Refit.SystemTextJsonContentSerializer.Deserialize[T](Byte[] buffer, Int32 length, JsonSerializerOptions jsonSerializerOptions) in C:\dev\refit\Refit\SystemTextJsonContentSerializer.cs:line 130
   at Refit.SystemTextJsonContentSerializer.<DeserializeAsync>d__4`1.MoveNext() in C:\dev\refit\Refit\SystemTextJsonContentSerializer.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Refit.RequestBuilderImplementation.<DeserializeContentAsync>d__15`1.MoveNext() in C:\dev\refit\Refit\RequestBuilderImplementation.cs:line 315
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in C:\dev\refit\Refit\RequestBuilderImplementation.cs:line 271
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
I see that it is not `Newtonsoft.Json.JsonReaderException` but I assume that it manifests in the same way using Newtonsoft.

**Comment by Rob-Houweling** [comment] 2020-12-09 09:26
I don't think it does, good to see it is better in the newer version though ;).
I am using the latest stable version which still uses the Newtonsoft lib. Is it possible for you to test with that version (5.2.4)? Or is that asking too much? :)

**Comment by Rassi** [comment] 2020-12-09 09:30
Here is a test using `NewtonsoftJsonContentSerializer` which produces the same `Newtonsoft.Json.JsonReaderException`:

```csharp
        [Fact]
        public async Task WithNonJsonResponseUsingNewtonsoftJsonContentSerializer_ShouldReturnApiException()
        {
            var settings = new RefitSettings
            {
                HttpMessageHandlerFactory = () => mockHandler,
                ContentSerializer = new NewtonsoftJsonContentSerializer()
            };

            var newtonSoftFixture = RestService.For<IMyAliasService>("http://api", settings);

            const string nonJsonResponse = "bad response";
            var expectedResponse = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(nonJsonResponse)
            };
            expectedResponse.Content.Headers.Clear();

            mockHandler.Expect(HttpMethod.Get, "http://api/aliasTest")
                       .Respond(req => expectedResponse);

            var actualException = await Assert.ThrowsAsync<ApiException>(() => newtonSoftFixture.GetTestObject());

            Assert.NotNull(actualException.Content);
            Assert.Equal(nonJsonResponse, actualException.Content);
        }
```

**Comment by Rassi** [comment] 2020-12-09 09:44
> I don't think it does, good to see it is better in the newer version though ;).
> I am using the latest stable version which still uses the Newtonsoft lib. Is it possible for you to test with that version (5.2.4)? Or is that asking too much? :)

I just tried getting tag `v5.2.4`, and using the test in https://github.com/reactiveui/refit/issues/966#issuecomment-741629307 I get the following:

```
Xunit.Sdk.ThrowsException
Assert.Throws() Failure
Expected: typeof(Refit.ApiException)
Actual:   typeof(Newtonsoft.Json.JsonReaderException): Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Refit.NewtonsoftJsonContentSerializer.<DeserializeAsync>d__4`1.MoveNext() in C:\dev\refit\Refit\NewtonsoftJsonContentSerializer.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Refit.RequestBuilderImplementation.<DeserializeContentAsync>d__15`1.MoveNext() in C:\dev\refit\Refit\RequestBuilderImplementation.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in C:\dev\refit\Refit\RequestBuilderImplementation.cs:line 270
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Rob-Houweling** [comment] 2020-12-09 10:30
Enough proof that it fails for now, I assume? Thanks @Rassi 

Hope you guys can fix it because it is really a pain in the behind to debug these kind of errors now.

**Closed** 2020-12-09 15:27 UTC
Labels: bug
