### ISSUE TITLE
Passing complex object or dictionary type in the Dynamic Header 

### ISSUE THREAD

**Issue by cemarchi** [reactiveui/refit#884] opened 2020-04-01 19:50 UTC
Hi,

Dynamic header is like static header, because you need to inform via method parameter the header name and its value. 

It would be very useful Dynamic Header is like Dynamic Querystring Parameters, where you create a complex class and  you create properties as you want and each one will be a attribute in the Header.

This example of complex header class:

`public class MyHeaderAttributes
{
    [AliasAs("User-Agent")]
    public string UserAgent{ get; set; }

    public int Authorization{ get; set; }
}

//that's the method declaration
[Get("/users/{user}")]
Task<User> GetUser(string user, [Header] MyHeaderAttributes header);
`

Another useful feature is instead of  complex object can be a dictionary like this:
`[Get("/users/{user}")]
Task<User> GetUser(string user, [Header] IDictionary<string, string> headers);`

Where each element of dictionary contains the header attribute (key) and its value.

Thank you very much!

**Comment by Dreamescaper** [comment] 2020-04-01 19:56
Probably duplicate of #197

**Closed** 2020-12-02 13:33 UTC
