### ISSUE TITLE
Singleton refit does not send all parallel requests

### ISSUE THREAD

**Issue by alextrukhan** [reactiveui/refit#449] opened 2018-03-03 10:45 UTC
Singleton refit does not send all parallel requests, only part of requests were sent. [Run example project](https://github.com/alextrukhan/Refit_SingletonIssue) to see issue. RunRefit method creates new instance of refit api for each request. RunRefitStatic uses static instance of refit api and static HttpClient. RunRefitWithSingleHttpClient uses static HttpClient and new instances of refit api for each request.
RunRefit works well but RunRefitStatic and RunRefitWithSingleHttpClient  do not work as expected. 

RunRefitStatic and RunRefitWithSingleHttpClient does only 2 request unlike RunRefit. When I use static HttpClient for parallel request everything is good.
Could I use singleton refit api or refit api with singleton HttpClient?

**Comment by bennor** [comment] 2018-03-13 06:39
Seems like a deadlocking issue. In theory you [should be using a singleton HttpClient](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/), and I've always done that myself in the past. It shouldn't matter whether you use a singleton Refit instance or a new one each time. 

I've never noticed a problem so this could be a regression (or perhaps I never issued simultaneous requests).

**Comment by robichaud** [comment] 2018-04-21 21:28
@bennor have you had an opportunity to look into this? I believe I am running into the same issue.

**Comment by Thorgard** [comment] 2018-08-06 14:39
Encountered the same issue.

**Comment by wrathofodin** [comment] 2019-07-15 10:45
Just tested it with https://github.com/canton7/RestEase and it has the same exact problem. I will see if I can find this nasty little bug...

**Comment by wrathofodin** [comment] 2019-07-16 20:47
What I observed today - this bug is not present in .NET Core. It's only present in .NET Framework. I will test with .NET Framework 4.8 later and update this comment. Any ideas?

**Comment by wrathofodin** [comment] 2019-07-19 10:07
OK I FOUND IT

Looks like this is `HttpClient` issue and not a Refit issue (RestEase has the same problem - coincidence? - no). `HttpCompletionOption.ResponseHeadersRead` is causing this. `HttpCompletionOption.ResponseContentRead` is the default.

https://github.com/reactiveui/refit/blob/806cab2e643bbe3758447704df6a73e5ef52f8eb/Refit/RequestBuilderImplementation.cs#L250

It's not present in .NET Core - which proves it's .NET Framework BCL bug.

**Comment by bennor** [comment] 2019-07-23 00:27
So definitely looks like our bug. IIRC RestEase was originally forked (or copied) from Refit by some people who wanted features we weren't prepared to add, so it's possible they inherited the same bug.

**Comment by wrathofodin** [comment] 2019-07-24 09:01
I don't think it's a bug. Caller has to dispose `HttpResponseMessage` and that's it. Unless it deadlocks with custom response types.

https://github.com/reactiveui/refit/blob/master/Refit/RequestBuilderImplementation.cs#L253-L261

**Comment by canton7** [comment] 2020-12-27 12:06
>  IIRC RestEase was originally forked (or copied) from Refit by some people who wanted features we weren't prepared to add, so it's possible they inherited the same bug.

Just to set the record straight: RestEase is inspired by Refit (I liked the way of declaring an interface to represent an API), but is a ground-up project: there's no shared code, it's not a fork, and I've never read the Refit source. I wrote it because the stubs generation in Refit kept breaking, and writing something that used S.R.E. sounded like a fun weekend project. It kind of snowballed from there.

**Comment by clairernovotny** [comment] 2021-02-04 23:17
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:17 UTC
Labels: bug
