### ISSUE TITLE
System.TypeLoadException has been thrown

### ISSUE THREAD

**Issue by afbase** [reactiveui/refit#412] opened 2018-01-26 05:46 UTC
Hello, 

Consider this my first time participating in this project.   

# What's Happening?
I'm running into a `System.TypeLoadException` when running my Xamarin iOS app in Visual Studio for Mac 2017.   

I get the error in my `FinishedLaunching` method of the AppDelegate at:
`            return base.FinishedLaunching(app, options);
`
in 
```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    JsonConvert.DefaultSettings =
    () => new JsonSerializerSettings()
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver(),
        Converters = { new StringEnumConverter() }
    };

    global::Xamarin.Forms.Forms.Init();

    LoadApplication(new App());

    return base.FinishedLaunching(app, options);
}  
```
The error states:
```System.TypeLoadException has been thrown```
```Could not resolve type with token 0100003b (from typeref, class/assembly Refit.RestService, Refit, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null)```

# What am I trying to do?

I'm using Clearbit's Autocomplete API ([link](https://clearbit.com/docs#autocomplete-api)) which if called like so:
```curl 'https://autocomplete.clearbit.com/v1/companies/suggest?query=stripe'```
should give a response something like this:

```
[
  {
    "name": "Segment",
    "domain": "segment.com",
    "logo": "https://logo.clearbit.com/segment.com"
  },
  {
    "name": "Segmentify",
    "domain": "segmentify.com",
    "logo": "https://logo.clearbit.com/segmentify.com"
  }
]
```
## Using Refit to call this API in an app

I did my best to follow the guidelines in the README.md.  First I created an interface in my Xamarin PCL project: 
```
public interface IClearbitAutocomplete
{
        [Get("/v1/companies/suggest?query={name}")]
        Task<List<IDataSourceIOS>> GetLogo(string name);
}
```
Next in my iOS Project, I created a ListViewRenderer which utilizes the `RestService`:
```
public class NativeiOSListViewRenderer : ListViewRenderer
{
    protected override void OnElementChanged(ElementChangedEventArgs<ListView> e)
    {
        base.OnElementChanged(e);

        if (e.OldElement != null)
        {
            // Unsubscribe
        }

        if (e.NewElement != null)
        {
            var ClearBit = RestService.For<IClearbitAutocomplete>("https://autocomplete.clearbit.com").GetLogo("Nike");
            ClearBit.Wait();
            var nlv = e.NewElement as NativeListView;
            nlv.Items = ClearBit.Result;
            Control.Source = new NativeiOSListViewSource(nlv);
        }
    }
} 
```
## How might this error be happening

In debug mode I see I can see the the Listview is trying to load and the error describe pops up.  I've done it so I comment out all references of the `ClearBit` object except for `var ClearBit = RestService.For<IClearbitAutocomplete>("https://autocomplete.clearbit.com").GetLogo("Nike");` and I still can reproduce the error.  

So I think this is the line in my code which causes the error but I'm not sure.

# My Setup
Refit Xamarin.iOS Package Version: 4.1.0.0
Xamarin.Forms Version: 2.5.0.122203

**Comment by onovotny** [comment] 2018-01-26 13:58
Couple of things to note:

1. In general, I would not create a new RestService instance in an event handler on a controller/view. I'd usually create those in a constructor or DI container.
2. Calling `.Wait()` or `.Result` on async methods/Tasks can usually lead to deadlocks. 

Neither of those explains a `TypeLoadException`. 

Can you please reproduce this in an isolated project so we can see what may be going on?

**Comment by afbase** [comment] 2018-01-26 15:54
>Can you please reproduce this in an isolated project so we can see what may be going on?

Should this all be in one project (iOS only) for isolation instead of a solution?  

I'm using an isolated solution (PCL + iOS projects) that just calls the API with refit and tries to load the result in a list view.  I came across the issue in a much larger solution; this `TypeLoadException` was something I had never seen before so I decided to create an isolated solution to reproduce/fix the error there first before using it in the real solution.

>1. In general, I would not create a new RestService instance in an event handler on a controller/view. I'd usually create those in a constructor or DI container.
2. Calling .Wait() or .Result on async methods/Tasks can usually lead to deadlocks.

Okay, I will rewrite my code to make sure I'm using best practices.

Thank you for responding!

**Comment by onovotny** [comment] 2018-01-26 15:55
however you can reproduce it is fine.

**Comment by bennor** [comment] 2018-01-26 19:09
> Should this all be in one project (iOS only) for isolation instead of a solution?

It doesn't have to be a single project, but you may need to directly reference Refit in the project that is the app's entry point. (Do this by adding the NuGet package to that project as well.)

**Comment by afbase** [comment] 2018-01-27 06:31
So I threw the async call of Refit into the constructor of the listviewrenderer like so:
```
public class NativeiOSListViewRenderer : ListViewRenderer
{
    List<IDataSource> ListViewItems { get; set; }
    public NativeiOSListViewRenderer()
    {
        Task.Run(async () =>
        {
            ListViewItems = await RestService.For<IClearbitAutocomplete>("https://autocomplete.clearbit.com").GetLogo("Nike");
        });
    }

    protected override void OnElementChanged(ElementChangedEventArgs<ListView> e)
    {
        base.OnElementChanged(e);

        if (e.OldElement != null)
        {
            // Unsubscribe
        }

        if (e.NewElement != null)
        {
            var nlv = e.NewElement as NativeListView;
            nlv.Items = ListViewItems;
            Control.Source = new NativeiOSListViewSource(nlv);
        }
    }
}
```
The good news is I don't get the `TypeLoadException` anymore.  The bad news is I don't get any errors or results but an empty listview.  I know I should expect several results from querying nike:
```
curl 'https://autocomplete.clearbit.com/v1/companies/suggest?query=Nike' | jq .

[
  {
    "name": "Nike",
    "domain": "nike.com",
    "logo": "https://logo.clearbit.com/nike.com"
  },
  {
    "name": "Nike Brasil",
    "domain": "nike.com.br",
    "logo": "https://logo.clearbit.com/nike.com.br"
  },
  {
    "name": "NikeSlayer",
    "domain": "nikeslayer.com",
    "logo": "https://logo.clearbit.com/nikeslayer.com"
  },
  {
    "name": "Nike Vision",
    "domain": "nikevision.com",
    "logo": "https://logo.clearbit.com/nikevision.com"
  },
  {
    "name": "NikeLeBron.net",
    "domain": "nikelebron.net",
    "logo": "https://logo.clearbit.com/nikelebron.net"
  }
]
```
I tried stepping through in debug mode and it looks like my `ListViewItems` is not getting set in the constructor as I would expect.  Am I missing something here?

**Comment by clairernovotny** [comment] 2021-02-04 23:19
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:19 UTC
