### ISSUE TITLE
[BUG] RefitStubs.g.cs is generated when it shouldn't

### ISSUE THREAD

**Issue by ittennull** [reactiveui/refit#811] opened 2019-12-16 07:03 UTC
C# library uses Refit. F# application references that library. When I compile F# - it fails with error: "RefitStubs.g.cs' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli."

It worked before with Refit v4.6.58, all next versions are broken. Here is the demo with the error https://gitlab.com/ittennull/refiterrorinfsharp

**Steps To Reproduce**
Compile the project from the link above, it fails. Edit ClassLibraryWithRefit.csproj and uncomment version  4.6.58 - now it works.

**Expected behavior**
Works with newer versions. RefitStubs.g.cs shouldn't be created for projects that don't directly depend on Refit

**Environment**
- OS:       Linux 5.4.2-1-MANJARO x64
- Net Core SDK: 3.1.100

**Comment by onovotny** [comment] 2019-12-16 14:16
This is caused by the targets in the `buildTransitive` folder. We need to check the project type before invoking the task in the target.

**Comment by benjaminhowarth1** [comment] 2019-12-20 12:47
I'm briefly re-opening this as somebody has kindly pointed out a better variable for declaring language type, $(Language)

**Comment by benjaminhowarth1** [comment] 2019-12-20 13:03
Merged and now closed.

**Closed by benjaminhowarth1** 2019-12-20 13:03 UTC
Labels: bug
