### ISSUE TITLE
Base Interface Implementation "doesn't look like a Refit interface" error

### ISSUE THREAD

**Issue by kenfolza** [reactiveui/refit#937] opened 2020-06-09 06:58 UTC
**Describe the bug**
We have a base interface for crud operations. 
This interface defines GetAll, Get, Save and Delete methods and it's implemented by all api interfaces.
If an api interface which implements IBaseApi doesn't contain a different method definition, base intetface api calls (getall(), get() etc...) doesn't work. An exception is being fired about a suitable refit method not found. 

"ISampleApi doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project."

If i define a dummy method, then it works.

**Steps To Reproduce**
```
    [Headers("Content-Type : application/json")]
    public interface IBaseApi<TModel, TKey> where TModel : BaseModel<TKey>
    {
        [Get("/getAll")]
        Task<ApiResult<List<TModel>>> GetAll();
        [Get("/get/{id}")]
        Task<ApiResult<TModel>> Get(TKey id);
        [Post("/save")]
        Task<ApiResult<TKey>> Save(TModel model);
        [Delete("/delete/{id}")]
        Task<ApiResult<int>> Delete(TKey id);
    }
```

```
    [Headers("Content-Type : application/json")]
    public interface ISampleApi : IBaseApi<SampleModel, int>
    {
          //Get(), GetAll() methods not working
    }
```
```
    [Headers("Content-Type : application/json")]
    public interface ISampleApi : IBaseApi<SampleModel, int>
    {
        //Get(), GetAll() methods are working
        [Get("/DummyMethodForRefit")]
        Task<int> DummyMethodForRefit();
    }

```
I don't want to define dummy methods for all interfaces.

Thank you,

**Comment by abobr** [comment] 2020-06-16 16:10
+1

**Comment by jamiehowarth0** [comment] 2020-06-18 00:16
@abobr closing as a duplicate of #775 - we're aware this is lacking in Refit's current implementation.

**Closed by jamiehowarth0** 2020-06-18 00:16 UTC
Labels: bug

**Comment by abobr** [comment] 2020-06-18 05:14
@jamiehowarth0 thanks for letting know

**Comment by kenfolza** [comment] 2020-06-18 06:40
Thank you,
