### ISSUE TITLE
'System.ObjectDisposedException' on awaiting a API method

### ISSUE THREAD

**Issue by hRupanjan** [reactiveui/refit#709] opened 2019-07-12 10:45 UTC
**Describe the bug**

I got this Exception

```{System.ObjectDisposedException: Cannot access a closed Stream.
  at System.IO.MemoryStream.CopyToAsync (System.IO.Stream destination, System.Int32 bufferSize, System.Threading.CancellationToken cancellationToken) [0x00042] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
  at Xamarin.Android.Net.AndroidClientHandler.WriteRequestContentToOutput (System.Net.Http.HttpRequestMessage request, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken) [0x0009a] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Xamarin.Android.Net.AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState) [0x002f4] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x002be] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0``2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <7208242e8171474ea12db9d506d0c43f>:0 
  at Ser.WebAPIs.LoginApiService.Login (Ser.Models.MobileLoginParam loginCredential) [0x00035] in C:\Ser\Ser\Ser\WebAPIs\LoginApiService.cs:36 }
```

while executing this

```    
public async Task<CWebResponse> Login(MobileLoginParam loginCredential)
        {
            CWebResponse response = null;
            try
            {
                response = await loginApi.Login(JsonConvert.SerializeObject(loginCredential));
            }
            catch (ApiException ex)
            {
                response = new CWebResponse { StatusCode = (CStatusCodes)ex.StatusCode, ErrorMessage = ex.Message };
            }
            catch (Exception e)
            {
                response = null;
            }
            return response;
}
```

This 'Login' method was awaited if you want more info. I'm getting this error repeatedly.

**Environment**

- OS:       Android
- Version:   9 (Pie)
- Device:   Redmi Note 5 Pro

**Comment by Arlodotexe** [comment] 2019-07-15 19:40
I've also started getting this issue a lot. It appeared seemingly out of nowhere, and can happen on any API call I make. Looking through my Git history, I cannot for the life of me tell what I changed to cause it.

My app is now constantly crashing for about 4k users. It's very important that I fix this bug.

I've been able to catch the exception by running `response.EnsureSuccessStatusCode()` in a try/catch, but this only catches when the response has return data (I think? It's hard to tell) and it doesn't stop it from throwing outside the project and in the app.

I've managed to drill down the stack trace to here

![image](https://user-images.githubusercontent.com/9384894/61241607-77ebd800-a709-11e9-9f42-f0e16c0a3882.png)

It's all the same error, but the stack traces are usually different
![image](https://user-images.githubusercontent.com/9384894/61241988-3f98c980-a70a-11e9-8680-09419343b6cd.png)
![image](https://user-images.githubusercontent.com/9384894/61242586-b5e9fb80-a70b-11e9-9ef7-140ee7b23862.png)

**Environment**
OS: Windows 10 
Verified crashes on all builds between 15063 and 17763 (Creators update and May 2019 update): 
![image](https://user-images.githubusercontent.com/9384894/61242985-a28b6000-a70c-11e9-89bf-d5fdbaccf2a4.png)

Refit version: 4.5.6
Devices: Haven't found one yet that doesn't have this issue

**Comment by Arlodotexe** [comment] 2020-02-01 14:20
After months and months of testing, I think I've randomly stumbled into the solution.

I'm extending the `HttpClientHandler` with my own, so I can do custom stuff with every response. When something goes wrong, I don't want my app to throw an exception, so instead, I was returning an empty response, like so:
![image](https://user-images.githubusercontent.com/9384894/73593542-0750b100-44cb-11ea-8619-bde67978f6eb.png)

I think that the `emptyResponse` instance you see there may have been the cause of this `ObjectDisposedException`. Upon moving that bit of code _inside_ the `TrySend` method, where it gets recreated every time, Refit no longer throws the exception.

It's beyond me why the stack traces and call stack sent me on a goose chase when the answer was in plain sight, but nonetheless the problem has been more or less resolved. I'll update this thread if I happen to be wrong and it returns.

**Comment by clairernovotny** [comment] 2021-02-04 23:25
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:25 UTC
Labels: bug
