### ISSUE TITLE
"doesn't look like a Refit interface" when referencing a refit interface from a nuget package

### ISSUE THREAD

**Issue by adrianord** [reactiveui/refit#318] opened 2017-06-01 22:02 UTC
We have been trying to centralize a refit interface for an API we're making in WebApi, however, when we nugetize our interface and reference it in a different solution, it throws an exception saying that the interface doesn't look like a Refit interface.

 When we try to inherit the interface into an empty interface, the same thing happens, and unless we copy the entire interface over, the auto generated code fails. We don't want to have to copy and paste this interface around as it needs to be used in multiple different solutions.

**Comment by bennor** [comment] 2017-06-01 22:12
Refit needs access to the actual source of the interface to build a proxy for it.

The only way you'll be able to make this work is to include Refit via NuGet in a project that includes the interface .cs file, so it builds the proxy along with your assembly. You should then be able to include that package in other projects.

**Comment by Orca2040** [comment] 2017-06-01 22:29
@bennor Thank you for the quick response. We have Refit included in the project that we Nugetize but it has not worked. I don't believe the auto generated files get built till you call the RestService.For() method. When we build, we get the file, but is almost entirely empty, only generating the RefitInternalGenerated namespace.

**Comment by bennor** [comment] 2017-06-01 22:43
They absolutely do get built at build time. They have to for iOS support. It's possible the Refit targets that run the code generation haven't been referenced in the csproj for your project.  Could be a .NET version thing in your project? Can you give us some more detail.

**Comment by Orca2040** [comment] 2017-06-01 22:47
Ah, I see. We are missing the target from our csproj, I wonder why that is? We're on .Net 4.6.1, Refit 2.4.1.

So best solution is to just include the proxy in the solution when it gets built in the build?

**Comment by bennor** [comment] 2017-06-01 22:52
Yeah, if your NuGet package includes the implementation for the interface that we generate using the build target, any projects depending on your package shouldn't have a problem. (There shouldn't be any functional difference between using NuGet or just having your Refit interfaces in a separate project in your solution.)

My suggestion would be to have a look through the csproj for any other of your projects that reference Refit, and copy the target section over.

**Comment by Orca2040** [comment] 2017-06-01 23:03
I have copied this line from one of our other projects 
` <Import Project="..\packages\refit.2.4.1\build\portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10\refit.targets" Condition="Exists('..\packages\refit.2.4.1\build\portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10\refit.targets')" />`

but we still seem to only be getting the namespace from the generated code.

**Comment by Orca2040** [comment] 2017-06-02 14:16
@bennor We figured it out, refit doesn't like us using nameof in the Get annotation.

**Comment by Orca2040** [comment] 2017-06-02 15:44
@bennor Every seems to work as intended after we removed nameof and renugetized things, no need to play around with the proxy generation.

**Comment by onovotny** [comment] 2017-06-02 21:47
Can you please provide a sample test case? I just updated the Roslyn parser in master and I'd like to validate this scenario.

**Comment by otto-gebb** [comment] 2018-10-05 11:35
I get this error when I break the string in an argument of an attribute line this:

```
// Works.
[Get("long_string")]

// Fail.
[Get("long_string_part_1"
    + "long_string_part_2")]
```

**Comment by antmeehan** [comment] 2018-11-28 12:10
Here's a failing test for the use of `nameof`.

Using v4.6.58 targeting `net472`.
````
[TestFixture]
public class UsingNameOfFails
{
	public interface MyInterface
	{
		[Post("/api/" + nameof(Add))]
		Task<int> Add(int x, int y);
	}

	[Test]
	public void ShouldCreateProxy()
	{
		// Act
		var proxy = RestService.For<MyInterface>("http://blah.com");

		// Assert
		Assert.IsNotNull(proxy);
	}
}
````

**Comment by alrz** [comment] 2019-09-21 10:51
It doesn't work with constants either. it's extremely useful to use constant paths e.g to use in test cases.

**Comment by MelbourneDeveloper** [comment] 2020-01-23 20:53
@adrianord , I'm getting this issue. I suspect that the validation message doesn't tell the whole story. I have a .NET Core 3.1 unit test project where I've freshly installed Refit from the NuGet gallery. I get the error message. This is my code:

```
public interface IGetPeople
{
    [Get("/JsonPerson/people")]
    Task<List<Person>> GetPeopleAsync();
}
```

Usage:
```
var client = RestService.For<IGetPeople>("https://localhost:44337");
```

> 'IGetPeople doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.'

**Comment by MelbourneDeveloper** [comment] 2020-01-23 21:06
@onovotny  Actually, the sample directly from the front page of this repo doesn't work either. 

```cs
public interface IGitHubApi
{
    [Get("/users/{user}")]
    Task<User> GetUser(string user);
}
```

```
var gitHubApi = RestService.For<IGitHubApi>("https://api.github.com");
```

Exactly the same error.

**Comment by MelbourneDeveloper** [comment] 2020-01-25 23:31
@onovotny my problem turned out to be a problem regarding the platform. The unit tests were for .NET Core 3.1.0. I created a new set of tests on the same platform and it behaved fine. I then realised that I had an unnecessary `#if` in the code (#NETCOREAPP3_1). When I removed this, the problem went away. It doesn't make much sense, but if I get time, I will try to create a sample to demonstrate the issue.

**Comment by funkyspider** [comment] 2020-03-03 13:41
I received this exception when I stupidly added double set of parenthesis around the Http Attribute.  I blame resharper for being helpful.  Took me a few minutes to notice. 

This failed with double parenthesis
` [Get(("/SiteParameters"))]`

Should of course be
`[Get("/SiteParameters")]`

Someone else may be daft enough to do this.

**Comment by clairernovotny** [comment] 2021-01-23 23:06
Closing due to age. Please file new issues based on v6.0-preview.84 or later as they occur.

**Closed by clairernovotny** 2021-01-23 23:06 UTC
Labels: semantic-analysis
