### ISSUE TITLE
Json Serializing extra properties on Post

### ISSUE THREAD

**Issue by jordanpowell88** [reactiveui/refit#372] opened 2017-09-26 14:51 UTC
I am trying to post using Refit and keep getting a 500 error. The Object that I am posting if I JsonConvert.SerializeObject(model) looks fine but when I pass the model into my Refit Interface I get the following: a 275 before and a 0 after the json

`275
{
all my model properties
}
0`

Heres my Refit Interface:
`[Post("/api/Url/{id})]
Task<HttpResponseMessage> PostModel([Body] Model model, string id);
`

See Attachments
![refit](https://user-images.githubusercontent.com/3605268/30866866-68058470-a2a8-11e7-9b15-93b70c76048c.PNG)

**Comment by bennor** [comment] 2017-09-26 20:21
By default, Refit uses the global JSON.NET `JsonSettings`, so if you've modified them in any way, it could be the cause.

Otherwise we'd need a fair bit more information to help with this - can you create a small repro project? What sort of environment is this happening in?

**Comment by jordanpowell88** [comment] 2017-09-28 14:15
I haven't changed any of the JsonSettings. It is happening in Core 2.0 with Angular 4.

**Comment by TuncBeyhan** [comment] 2017-10-17 12:57
You'll see Transfer-Encoding : chunked if you look at the raw message. I guess your server can't handle chunked messages. ( probably .net 4 web api 2+)

**Comment by droosma** [comment] 2017-10-20 11:43
I am running in to the following situation. I have a Web API 2 (framework 4.6.) application that i wrote a .netstandard1.4 client library for. If i grab the newest nuget version 4.0.1 from nuget.org and run that in a coreapp2.0 console application Post does not work. If i build the package from the source code itself (4.0.2-build.43) it works again. but the strange thing is i can't really find any code changes. I would expect `ret.Headers.TransferEncodingChunked = true;` some where [here](https://github.com/paulcbetts/refit/blob/master/Refit/RequestBuilderImplementation.cs#L115)

**Comment by nullsync** [comment] 2017-11-02 17:42
I am having the exact same issue in .netcoreapp2.0 with refit 4.0.1, on post methods i get the same result as the OP

**Comment by ryanbuening** [comment] 2017-11-14 13:15
Same issue here with Refit version 4.0.1 using .NET Core 2.0.

**Comment by Cheesebaron** [comment] 2017-11-14 15:35
Can either of you make a repro sample I can test with?

**Comment by peters** [comment] 2017-11-16 13:29
@jordanpowell88 You have to explicitly set Content-Length in your `HttpClientHandler` if the destination server does not support chunked transfers. I recently had to deal with some ancient piece of crap API leading me towards this issue. @paulcbetts I guess this should be handled by the user because `streams` ?

**Comment by bennor** [comment] 2018-01-26 21:36
If the issue is related to the missing `Content-Length` header, you can [fix it using version 4.1.0](https://github.com/paulcbetts/refit#buffering-and-the-content-length-header).

**Comment by mac2000** [comment] 2018-02-11 13:11
There is a chance that I have something similar / related so goin to post it here:

In my case API is waiting something like:

```json
{
  auth: {
    time: "2018-02-02 21:59:00",
    sign: "**********" // result of md5(time + secret)
  },
  payload: {...} // actual request
}
```

I wish interface only required from user is to give `payload` and whole auth block to be calculated / prepended on the flight before sending request

is it possible with current implementation?

**Comment by onovotny** [comment] 2018-02-11 13:54
@mac2000 that's not possible today. I would suggest using a wrapper class to implement the functionality you need.

**Comment by mac2000** [comment] 2018-02-11 17:12
Yep seems like a trust, other way me be to mess around with http client handler by wrapping and replacing request content but it looks ugly. Thank you in advice

**Comment by erlandvr** [comment] 2019-03-19 21:06
When will this be fixed?

**Comment by clairernovotny** [comment] 2021-02-04 23:48
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:48 UTC
