### ISSUE TITLE
[BUG] ApiResponse<T> returns "null" value if I use in API action "return Ok()" or "NoContent()"

### ISSUE THREAD

**Issue by ibalmaci** [reactiveui/refit#905] opened 2020-04-17 06:24 UTC
When I use Refit version 4.6.58, both of methods below was returning ApiResponse value. 

I upgraded my version to 5.1.67. And I started to get "**null**" value from Test1Async() method. On v4.6.58, two methods return ApiResponse value, too. On v.5.1.67, Test2 method returns ApiResponse value, but Test1 method returns **null** value.

```
//My interface:
public interface ITest
    {
        [Get("/api/test1")]
        Task<ApiResponse<object>> Test1Async();

        [Get("/api/test2")]
        Task<ApiResponse<object>> Test2Async();
    }

//API Controller:
[HttpGet]        
public async Task<IActionResult> Test1Async()
{
     return Ok();    //v4.6.58 [value]  , v5.1.67 null
     // or
     return NoContent();    //v4.6.58 [value]  , v5.1.67 null
     // or
     return BadRequest();   //v4.6.58 [value]  , v5.1.67 [value]
}

[HttpGet]        
public async Task<IActionResult> Test2Async()
{
     return this.Ok(new ContentResult {StatusCode = 200 });  // [value] all versions
}

```

**Comment by Dreamescaper** [comment] 2020-04-17 22:18
Trying to reproduce your issue.
Are you using default ContentSerializer?

**Comment by Dreamescaper** [comment] 2020-04-17 22:50
I cannot reproduce that.
It returns non-null `ApiResponse<object>` in all 3 cases for me.

Would be great if you'd be able to prepare some project to illustrate the issue.

**Comment by Wind010** [comment] 2020-04-23 01:43
@ibalmaci, I was hitting the same thing and suspected it may have been an issue with deserialization of the object.  Turns out it was indeed the wrong type specified in the Refit API interface compared to the actual object returned IActionResult<MyType> from the API.

**Comment by clairernovotny** [comment] 2021-02-04 23:42
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:42 UTC
Labels: bug
