### ISSUE TITLE
Ability to throw an ApiException for Tasks that returns HttpResponseMessage

### ISSUE THREAD

**Issue by karlomedallo** [reactiveui/refit#369] opened 2017-09-20 13:16 UTC
Hi,

I have a scenario where I need all failed calls to throw an ApiException. The problem is that if I set the response to HttpResponseMessage, it will not throw an ApiException. In the case where a Generic Type is used, it always throw the ApiException.

It does not need to be turned on by default, but at least it can be toggled through RefitSettings and hook that up in the block below:

https://github.com/paulcbetts/refit/blob/0147b2a2a1f73dd6f6bab548370db619883b5e67/Refit/RequestBuilderImplementation.cs#L380-L388

I'll just use the exact same code in:

https://github.com/paulcbetts/refit/blob/0147b2a2a1f73dd6f6bab548370db619883b5e67/Refit/RequestBuilderImplementation.cs#L390-L394

Do you think this will be something that Refit should support? I can make a PR if needed.

Thanks!

**Comment by clairernovotny** [comment] 2021-02-04 23:45
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Closed by clairernovotny** 2021-02-04 23:45 UTC

**Comment by igorgiovannini** [comment] 2021-03-03 21:27
@clairernovotny I can confirm this issue is still valid even with Refit v6.
If the return type of an endpoint is set to HttpResponseMessage, an ApiException is not thrown.
This would mean an extra overhead implementing a status code handling by our own.

See the following log entry as an example, no exception has been thrown

`[22:23:13 INF] (System.Net.Http.HttpClient.Refit.Implementation.Generated+healbitpheasyoServiceServicesSumexFileGeneratorISumexFileGeneratorApi, healbit.pheasyo.Service, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.LogicalHandler) End processing HTTP request after 1961.9762ms - 500  {EventId={Id=101, Name="RequestPipelineEnd"}, HttpMethod="POST", Uri=http://192.168.1.118:2836/api/Invoices, ActionId="eb3c221d-c051-4ac8-a1fc-1d78d0a894f0", ActionName="healbit.pheasyo.Service.Api.Financial.InvoicesController.UpdateSettingsAsync (healbit.pheasyo.Service)", RequestId="0HM6UH8QVSBRB:00000002", RequestPath="/api/v1/financial/invoices/0f7bbe8f3fce400f9d9b5bc8d2bc083e/settings", ConnectionId="0HM6UH8QVSBRB", Scope=["HTTP POST http://192.168.1.118:2836/api/Invoices"]}
`

**Comment by JFMG** [comment] 2021-03-05 15:29
@clairernovotny Please reopen this issue.
