### ISSUE TITLE
Refit Post Attribute Requires Literal Const

### ISSUE THREAD

**Issue by mackgammeter** [reactiveui/refit#500] opened 2018-06-12 14:33 UTC
Refit doesn't seem to like the constant reference. 
_[Post(WebApiActionsConsts.ValidateAsync)]_

Changing this to a literal string fixed things.
_[Post("/api/Invitation/ValidateAsync")]_

Is there a particular reason for this?

**Comment by bennor** [comment] 2019-01-10 22:55
Closing this as a duplicate of #263

**Closed by bennor** 2019-01-10 22:55 UTC
